#!/bin/dash
#
# Abstract front-end script for fetching a file using curl(1) or wget(1),
# producing a clean file-based interface for transfer status. This command is
# designed to be run in the background.
#
# Copyright 2022 Coastal Carolina University
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the “Software”), to
# deal in the Software without restriction, including without limitation the
# rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
# sell copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
# IN THE SOFTWARE.


# wrap_curl <URL> <output_file>
wrap_curl() {
    curl -o "$2" "$1" 2>&1 | tr '\r' '\n'
    # Filter TODO
    # cat firefox.log | tr '\r' '\n' | awk '/^[0-9]/ { print $3 }'
}


# wrap_wget <URL> <output_file>
wrap_wget() {
    wget -O "$2" --progress=dot "$1"
    # Filter TODO
    # grep '%' whatever.log | awk '{ for (i = 1; i <= NF; i++) { if ($i ~ /%$/) { print $i } } }'
}

