#!/bin/dash
#
# Downloads a single file, selecting a download mechanism based on the URL
# scheme and available backends.
#
# Copyright 2022 Coastal Carolina University
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the “Software”), to
# deal in the Software without restriction, including without limitation the
# rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
# sell copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
# IN THE SOFTWARE.


whatami=$(readlink -e "$0")
whereami=$(dirname "${whatami}")


usage() {
    cat << EOF
$0 [options] <URL> <output_path>

Options:
    -h | --help
        Show this help message and exit.
    -p <server> | --proxy <server>
        Use the specified proxy server to complete the download.
    -s <dir> | --status <dir>
        Use the specified directory for status files. Otherwise, a temporary
        directory is created with mktemp(1).

Downloads the requested file from <URL>, saving it to <output_path>. if the
<output_path> is a directory, then the filename from the <URL> is used as
the destination file within the directory. Upon starting the download, the
status directory path is printed on standard output.

The status directory contains information about the ongoing download. Each
download backend writes status information specific to the download tool.
Client code should run this program as a background task and periodically call
the update_progress script to parse the tool-specific status into a common
format that is useful for monitoring download progress.

File downloads are accomplished using a backend (such as curl or wget). The
backend search order can be controlled by setting the LIBTEAL_DOWNLOAD_BACKENDS
environment variable, which defaults to trying each supported backend in
lexical order.

Note that a backend must support the URL scheme, must support the proxy server
scheme if using a proxy, and be installed on the system in order to be
selected. The first matching backend in the search order will be used for the
download. If no suitable backend is available, an error will occur, and
nothing will be downloaded.

Advanced configuration of backends, including support for proxy server
authentication, must be performed using the respective backend's configuration
file. Different backends support different features, so the documentation for
each backend must be consulted to determine what settings are available and
where those settings should be stored.

Backends supported by this installation of libteal are:
EOF

    find "${whereami}" -type d -mindepth 1 -maxdepth 1 -printf ' * %f\n'
}


status_output=
proxy=
while [ $# -gt 0 ]; do
    case "$1" in
        -h|--help)
            usage
            exit 0
        ;;
        -p|--proxy)
            proxy="$2"
            shift 2
        ;;
        -s|--status)
            status_output="$2"
            shift 2
        ;;
        *)
            break
        ;;
    esac
done


if [ $# -ne 2 ]; then
    echo "Usage: $0 [options] <URL> <output_path>" >&2
    exit 2
fi


url="$1"
out_path="$2"

if [ -d "${out_path}" ]; then
    out_path=$(echo "${out_path}" | sed 's|/*$||')
    base_name=$(basename "${url}")
    out_path="${out_path}/${base_name}"
fi


# Quick sanity check for the output path:
parent=$(dirname "${out_path}")
if [ ! -d "${parent}" ]; then
    echo "Directory not found: ${parent}" >&2
    exit 1
fi


# Load the list of backends if they aren't explicitly specified in an environment variable
if [ -z "${LIBTEAL_DOWNLOAD_BACKENDS}" ]; then
    LIBTEAL_DOWNLOAD_BACKENDS=$(find "${whereami}" -type d -mindepth 1 -maxdepth 1 -printf '%f ')
fi


# Determine the URL scheme
if ! echo "${url}" | grep -q "://"; then
    echo "Invalid URL (missing scheme): ${url}" >&2
    exit 1
fi
scheme=$(echo "${url}" | awk -F '://' '{print tolower($1)}')


# Determine the proxy scheme, if any. When not using a proxy, set the scheme to "none" explicitly.
proxy_scheme=none
if [ -n "${proxy}" ]; then
    proxy_scheme=$(echo "${proxy}" | awk -F '://' '{print tolower($1)}')
fi


# Find the first matching backend that is installed on the system and can support our URL and proxy schemes
backend=
for item in $(echo "${LIBTEAL_DOWNLOAD_BACKENDS}"); do
    if [ -d "${whereami}/${item}" ]; then
        if "${whereami}/${item}/available" "${scheme}" "${proxy_scheme}"; then
            backend="${item}"
            break
        fi
    fi
done


# Be sure we have a backend before proceeding
if [ -z "${backend}" ]; then
    echo "No suitable backend found for scheme ${scheme} with proxy type ${proxy_scheme}" >&2
    echo "Tried ${LIBTEAL_DOWNLOAD_BACKENDS}" >&2
    exit 1
fi


# Create a temporary status directory if -s wasn't used
if [ -z "${status_output}" ]; then
    status_output=$(mktemp -d)
elif [ ! -d "${status_output}" ]; then
    echo "Directory not found: ${status_output}" >&2
    exit 1
fi
echo "${status_output}"


# Test write permissions by writing the backend name into the status directory
echo "${backend}" > "${status_output}/backend" || exit 1


# Now the actual downloading bit
"${whereami}/${backend}/download" "${status_output}" "${url}" "${out_path}" "${proxy}"
status=$?


# If the download failed, clean up the partial file
if [ ${status} -ne 0 ]; then
    rm -f "${out_path}"
    exit 1
fi


exit ${status}
